### PR TITLE
[TASK] make it possible to use in composer from git

### PR DESCRIPTION
**Pull request by anjeylink**

### CODE REVIEW

**Comment by kaystrobach** [comment]
thank you for your input, as CMS8 has native composer support, i think that this package is obsolete if you take a long look into the future.

**Comment by anjeylink** [comment]
you mean native yaml support ?

**Comment by kaystrobach** [comment]
basicly this package contains a simple dependency to symfony ... so you can require that on your own in your own composer.json 

See: https://github.com/kaystrobach/TYPO3.yaml_parser/tree/master/Resources/Private/PHP/vendor/symfony/yaml/Symfony/Component/Yaml

**Comment by anjeylink** [comment]
ok, thx

**Comment by kaystrobach** [comment]
http://symfony.com/doc/current/components/yaml.html

**Pull request merged**
